### ISSUE TITLE
Problem with MIS Budget in version 11

### ISSUE THREAD

**Issue by PrismeUser** [OCA/mis-builder#129] opened 2018-10-01 14:41 UTC
Hello,

I encouter the following problem with MIS-Builder regarding budget : 

When I go on Invoicing then I click Reporting and then MIS-Report 

Then I create a new report as follow : 
![image](https://user-images.githubusercontent.com/43753488/46295423-4ea5f500-c598-11e8-9786-4e92151d8bb9.png)

Then I Click on Colums and I click on "add Item"
![image](https://user-images.githubusercontent.com/43753488/46295523-90cf3680-c598-11e8-9f98-f426caf3657b.png)

Then when I click on save and close, I receive a Error with the following message : 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x3fff7d655d30>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4960, in onchange
    record = self.new(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4486, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4359, in _convert_to_cache
    for name, value in values.items()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4360, in <dictcomp>
    if name in fields
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2066, in convert_to_cache
    comodel.browse(command[1]).update(command[2])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4467, in update
    record[name] = value
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4671, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 966, in __set__
    value = self.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2059, in convert_to_cache
    ids = OrderedSet(record[self.name].ids if record.id else ())
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4662, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 948, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1049, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2565, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2509, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2628, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "virtual_41"
LINE 1: ...period" WHERE "mis_report_instance_period".id IN ('virtual_4...
                                                             ^
Me and my team did not manage to find any solution for this issue...
Please let me know if you have any solutions.

Thank you in advance for your help.

BR

Maxime

**Comment by sbidoul** [comment] 2018-10-01 15:37
Are you at the code sprint?

**Comment by PrismeUser** [comment] 2018-10-01 15:41
Hello Stéphane, 

Infortunately not...

Best regards,

Maxime Provini 

Envoyé depuis IBM Verse


   Stéphane Bidoul (ACSONE) --- Re: [OCA/mis-builder] Problem with MIS Budget in version 11 (#129) --- 
    De :"Stéphane Bidoul (ACSONE)" <notifications@github.com>A :"OCA/mis-builder" <mis-builder@noreply.github.com>Cc :"PrismeUser" <maxime.provini@prisme.ch>, "Author" <author@noreply.github.com>Date :lun., 1 oct. 2018 17:37Objet :Re: [OCA/mis-builder] Problem with MIS Budget in version 11 (#129)
  
  Are you at the code sprint?

**Comment by sbidoul** [comment] 2018-10-01 15:55
I could not reproduce on runbot.odoo-community.org. Could you try reproducing your scenario there? https://runbot.odoo-community.org/runbot/repo/github-com-oca-mis-builder-248

**Comment by PrismeUser** [comment] 2018-10-02 06:02
Hello Stéphane,

I just reproduced the procedure on runbot.odoo-community.org and it worked 
perfectely there... I don't understand why... maybe you'll have an 
explanation for this

Thank you in advance for your feedback.

Best regards,


Web: www.prisme.ch 
Tél: +41 79 481 49 35  
Maxime Provini
Prisme Solutions Informatique SA 
Rte de Montagny 11 
CH - 1772 Ponthaux

**Comment by sbidoul** [comment] 2018-10-02 06:41
Make sure you have the latest version of the mis-builder code, as well as the dependencies (date_range, etc). And maybe test on a fresh database. 

I'll close this as non reproducible. Feel free to reopen if you find more information.

**Closed as completed by sbidoul** 2018-10-02 06:41 UTC
Labels: bug, 11.0
