### ISSUE TITLE
consolidation in mis_ builder odoo V11

### ISSUE THREAD

**Issue by lili94** [OCA/mis-builder#218] opened 2019-07-25 08:31 UTC
hi i have tow company : CETIC and ENSI . CETIC is consolidation company i have 4 report in mis_builder and i want when the accounting enter to Cetic and consolidate ENSI they will have balance sheet with consolidation of the tow company , does mis_builder can do somthing like this ?

thanks for help
@sbidoul @fclementic2c @hitrosol

**Comment by sbidoul** [comment] 2019-09-29 14:38
Looks like a duplicate of #215

**Closed as completed by sbidoul** 2019-09-29 14:38 UTC
