### ISSUE TITLE
Error: QWeb2: Template 'FieldColor' not foun

### ISSUE THREAD

**Issue by alfaser123** [OCA/mis-builder#43] opened 2017-10-27 12:14 UTC
this happens when I want to create/edit a style. Due to this  I cannot generate any report also.

thanks for your help

**Comment by alfaser123** [comment] 2017-10-27 12:39
problem in file web_widget_color\static\src\js\widget.js

`odoo.define('web.web_widget_color', function(require) {
    "use strict";

    var core = require('web.core');
    var widget = require('web.form_widgets');
    var FormView = require('web.FormView');

    var QWeb = core.qweb;
    var _lt = core._lt;

    var _super_getDir = jscolor.getDir.prototype;
    jscolor.getDir = function () {
        var dir = _super_getDir.constructor();
        if (dir.indexOf('web_widget_color') === -1) {
            jscolor.dir = 'web_widget_color/static/lib/jscolor/';
        }
        return jscolor.dir;
    };

    var FieldColor = widget.FieldChar.extend({
        template: 'FieldColor',
        widget_class: 'oe_form_field_color',
        is_syntax_valid: function () {
            var $input = this.$('input');
            if (!this.get("effective_readonly") && $input.size() > 0) {
                var val = $input.val();
                var isOk = /^#[0-9A-F]{6}$/i.test(val);
                if (!isOk) {
                    return false;
                }
                try {
                    this.parse_value(this.$('input').val(), '');
                    return true;
                } catch (e) {
                    return false;
                }
            }
            return true;
        },`

**Comment by sbidoul** [comment] 2017-10-27 12:43
Which version do you use? 9.0, 10.0? Community or Enterprise?

**Comment by alfaser123** [comment] 2017-10-27 15:32
HI sbidoul.  I am using 10.0  community

**Comment by sbidoul** [comment] 2017-10-27 16:01
I can't reproduce. I went on runbot, Accounting > Configuration > MIS Reporting > Styles, and I could create and modify style color without problem. Can you provide more information?

**Comment by alfaser123** [comment] 2017-10-27 16:56
thanks. i just download MIS and installed you can access to  http://201.244.109.184:8003/
key: soporte/123

In runbot it runs well but i do not why in my version doesnot

**Comment by sbidoul** [comment] 2017-10-27 17:10
It seems there are missing files in your setup:

![image](https://user-images.githubusercontent.com/692075/32116328-7e9c9920-bb4a-11e7-86a5-b80f25fe0821.png)

**Comment by alfaser123** [comment] 2017-10-27 17:37
sbidoul  look at it:

![imagen](https://user-images.githubusercontent.com/29344513/32117148-e8450926-bb12-11e7-98bb-464b3e596a69.png)

In that file is where the code appeared asking for the template . I am not expert in  code

I installed in other folder different to odoo/addons/   it is possible this could be de problem?

thannks a lot

**Comment by alfaser123** [comment] 2017-10-27 18:42
sbidoul  I just realized you are the author of MIS, great job!!. Amazing. Congratulations and thanks for share it.

I installed on addons folder and  the problem continues. Same error at creating Style.
any idea what should I check? thanks 
![imagen](https://user-images.githubusercontent.com/29344513/32119966-82bc512c-bb1c-11e7-8ae5-e00c1201a9a4.png)

**Comment by sbidoul** [comment] 2018-03-11 10:07
Closing as it is most probably a local deployment issue. Feel free to reopen if you believe there is actually a bug.

**Comment by josepmy** [comment] 2019-07-15 23:10
Hi, I have the same issue. I installed the module, the report works but if I try to open an style from the config menu appear the error. I'm on V12 CE
Any help?

**Comment by josepmy** [comment] 2019-07-15 23:17
If I try to create a new style I get the same error.
I'm on V12 CE

**Comment by djoq** [comment] 2019-07-26 04:13
I have the same issue too! Please, any error bubbling is not helping :( I am on V11 community.

**Comment by josepmy** [comment] 2019-07-26 05:24
Hi Daniel,

After restart odoo my error was gone. I don’t know why but now I can edit the styles.

**Comment by djoq** [comment] 2019-07-26 05:49
I uninstalled impacto and things worked fine.

**Comment by josepmy** [comment] 2019-07-26 05:54
Great. What is “impacto”?

**Comment by djoq** [comment] 2019-07-26 05:56
A theme that must have a dependency on the module causing errors for us.

**Comment by josepmy** [comment] 2019-07-26 05:57
OK. I understand. Great that now is working

**Closed as completed** 2023-03-17 12:08 UTC
Labels: question
