### ISSUE TITLE
Expand by AA

### ISSUE THREAD

**Issue by hitrosol** [OCA/mis-builder#392] opened 2021-12-05 06:03 UTC
Having MIS Budgets (by Accounts) is a great feature, so we can expand or collapse the Accounts Details by set the Disable account details expansion. 

It would be greater if we have the expansion feature by AA, so we don't have to make specific AA as KPI. This will help user if they have many KPI based on AA. 

I'm thinking to have the MIS Builder Analytic Items and put that as basic of for MIS Budgets (by AA) ?

**Comment by TeoGoddet** [comment] 2021-12-16 23:07
This seems to require a lot of work, what need to be done is discussed in #115

**Comment by sbidoul** [comment] 2022-07-20 17:00
Closing as duplicate of #115

**Closed as completed by sbidoul** 2022-07-20 17:00 UTC
Labels: enhancement
