### ISSUE TITLE
error while mixing kpis and subkpis (and managed to get  "Probably not your fault... but I'm really curious to know") 

### ISSUE THREAD

**Issue by aminesoulaymani** [OCA/mis-builder#125] opened 2018-09-17 09:52 UTC
I got an error, while my logs doesn't show anything special, so i cannot actually describe it.
how to reproduce this error:
1-create a mis builder template with: 1 subkpis. no queries. add a kpi with "multi" ticked, add the previous subkpi, put a number as expression; value type, comparison method and so doesn't matter. add another kpi, put a number as expression, other options doesn't matter either.
2- create a report, select your template, click on preview. everything perfect, it should work.
3- now go back to the template, add another subkpi. actually, there is no need to add it to the main kpi, the related report should crash if you try to preview it. adding the new subkpi to any kpi results the same crash and message "Probably not your fault... but I'm really curious to know how you managed to raise this error so I can handle one more corner case!"

best regards

 Odoo 10.0-20171015 (Community Edition)
MIS Builder 10.0.3.1.1 
Mis Budget not installed.

**Comment by sbidoul** [comment] 2018-09-17 11:08
Thanks for the detailed scenario. I'll try to reproduce as soon as possible.

In the meantime could you try the same with #116 and tell me if it works better?

**Comment by sbidoul** [comment] 2018-10-01 15:56
@aminesoulaymani #116 is now merged. Could you try again?

**Comment by sbidoul** [comment] 2019-05-20 09:23
Closing since no feedback. Check #116 and #196.

**Closed as completed by sbidoul** 2019-05-20 09:23 UTC
Labels: bug, 10.0
